Module7 task1
htmlacademy-react/839417-what-to-watch-9 pull request #10
Opened 2022-03-26 09:15 UTC by Dimahtml

2022-03-26 17:59 UTC, bini1988 requested changes
Нужно убрать места с вызовами `store.dispatch` и обернуть в `useEffect` запросы внутри компонента

2022-03-26 17:59 UTC, bini1988 commented on project/src/components/pages/main-screen/main-screen.tsx
> +          && <ShowMoreBtn onClickHandler={onClickHandler} />}
По [соглашению](https://jaketrent.com/post/naming-event-handlers-react)

`<ShowMoreBtn onClick={onClickHandler} />`

2022-03-26 17:59 UTC, bini1988 commented on project/src/components/pages/movie-screen/movie-screen.tsx
> +  }
Чтобы получить функцию `dispatch` нужно использовать хук `useDispatch` плюс в рендер функции компонента не должно быть вызовов функций с сайдэффектами, их нужно оборачивать в `useEffect`

2022-03-26 17:59 UTC, bini1988 commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilmAction());
Хорошей практикой будет делать эти запросы только при необходимости, чтобы не загружать весь список фильмов если пользователь открыл сайт на странице фильма

2022-03-26 17:59 UTC, bini1988 commented on project/src/store/api-actions.ts
> +    store.dispatch(loadFilms(data));
Давай брать `dispatch` и `api` из аргументов функции как описано в документации к [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk#payloadcreator)

2022-03-26 17:59 UTC, bini1988 commented on project/src/store/reducer.ts
> +const blankFilm = {
А для чего нужен этот объект? Почем в `promoFilm` просто не хранить `undefined` или `null` ?

2022-03-27 03:14 UTC, Dimahtml commented on project/src/store/reducer.ts
> +const blankFilm = {
Потому что иначе ТС ругается, что `object possible null` и пошло-поехало...

2022-03-27 04:07 UTC, Dimahtml commented on project/src/components/pages/movie-screen/movie-screen.tsx
> +  }
Функция с сайдэффектом здесь - это `dispatch`?

2022-03-27 04:11 UTC, Dimahtml commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilmAction());
Как это сделать? Поместить внутрь компонента MainScreen?

2022-03-27 05:02 UTC, Dimahtml commented on project/src/store/api-actions.ts
> +    store.dispatch(loadFilms(data));
Читал документацию, не понял что нужно поменять. Я делал как в лекции показывали.

2022-03-27 09:09 UTC, bini1988 commented on project/src/components/pages/movie-screen/movie-screen.tsx
> +  }
Да

2022-03-27 09:10 UTC, bini1988 commented on project/src/index.tsx
> +store.dispatch(fetchPromoFilmAction());
Да

2022-03-27 10:03 UTC, bini1988 commented on project/src/store/api-actions.ts
> +    store.dispatch(loadFilms(data));
Вот пример из учбного [проекта](https://github.com/htmlacademy-react/guess-melody-9/blob/master/project/src/store/api-actions.ts#L30)

2022-03-28 13:33 UTC, bini1988 commented on project/src/components/pages/main-screen/main-screen.tsx
> +          && <ShowMoreBtn onClickHandler={onClickHandler} />}
Вот еще критерий на этот случай https://up.htmlacademy.ru/react/9/criteries#d2

2022-03-28 13:37 UTC, bini1988 approved these changes

2022-03-28 13:37 UTC, bini1988 commented on project/src/components/pages/main-screen/film-promo/film-promo.tsx
> +        {promoFilm && <img src={promoFilm.backgroundImage} alt={promoFilm.name} />}
В новом стандарте можно использовать запись вида
`<img src={promoFilm?.backgroundImage} alt={promoFilm?.name} />`

2022-03-28 13:37 UTC, bini1988 commented on project/src/components/pages/main-screen/main-screen.tsx
>    const onClickHandler: MouseEventHandler<HTMLButtonElement> = () => {
handleClick

2022-03-28 13:38 UTC, bini1988 commented on project/src/components/pages/main-screen/main-screen.tsx
>    const onClickHandler: MouseEventHandler<HTMLButtonElement> = () => {
Вот еще критерии на этот случай https://up.htmlacademy.ru/react/9/criteries#d2 и https://up.htmlacademy.ru/react/9/criteries#d9

2022-03-28 13:38 UTC, merged